idf_component_register(
    SRCS
        "main.c"
        "board/board_power.c"
        "board/board_keys.c"
        "ui/led_status.c"
        "ui/ble_pairing_gesture.c"
        "ui/device_mode_selector.c"
        "ui/tempo_selector.c"
        "system/device_mode_boot.c"
        "ble/beatbox_ble.c"
        "audio/audio_click.c"
        "seq/tempo.c"
        "seq/pattern.c"
        "seq/sequencer.c"
        "host/host_link.c"
    INCLUDE_DIRS
        "."
        "board"
        "audio"
        "seq"
        "ui"
        "system"
        "ble"
        "host"
    REQUIRES
        esp_driver_pcnt
        esp_driver_gpio
        esp_driver_i2s
        esp_driver_usb_serial_jtag
        esp_timer
        app_update
        bt
        mbedtls
        nvs_flash
    EMBED_FILES
        "audio/samples/kick.raw"
        "audio/samples/snare.raw"
        "audio/samples/hihat_closed.raw"
        "audio/samples/hihat_open.raw"
        "audio/samples/clap.raw"
        "audio/samples/rim.raw"
        "audio/samples/tempo_slow.raw"
        "audio/samples/tempo_original.raw"
        "audio/samples/tempo_fast.raw"
        "audio/samples/mode_beatbox.raw"
        "audio/samples/mode_easyinput.raw"
)
